safe: false
name: BrowserFIT
description: kickstart your responsive workflow

gaaccount: UA-45909125-1
domain: browserfit.github.io

author:
  name: Átila Fassina
  email: hey@atilafassina.com
  github: atilafassina
  twitter: atilafassina

include: ['.htaccess']
permalink: /:title
future: true
show_drafts: true
markdown: redcarpet
pygments: true
